# -*- coding: utf-8 -*-
"""MlfinalProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nSGX5nXTD39F8PdbgpJvGJr_fzWgMU_Y

## **CUSTOMER RETAIL MACHINE LEARNING PROJECT**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, confusion_matrix

"""**Load Dataset**"""

df = pd.read_csv("customer_retail csv file.csv")

print(df.head())

print(df.info())

print(df.shape)

"""**Check Dataset Columns**"""

print(df.columns)

"""**SELECT REQUIRED COLUMNS**"""

df = df[['Quantity', 'UnitPrice', 'Country']]

df.dropna(inplace=True)

"""**Handle Missing Values**"""

df.dropna(inplace=True)

print("\nMissing Values:")
print(df.isnull().sum())

"""**Data Preprocessing**

* **ENCODE COUNTRY COLUMN***
"""

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

df['Country'] = encoder.fit_transform(df['Country'])

print("\nDataset After Encoding:")
print(df.head())

"""**VISUALIZATION**
* **Customer Distribution Graph**
"""

plt.figure(figsize=(10,5))

df['Country'].value_counts().head(10).plot(kind='bar')

plt.title("Customer Distribution by Country")
plt.xlabel("Country")
plt.ylabel("Count")

plt.show()

"""**Split Dataset**"""

from sklearn.model_selection import train_test_split
X = df[['Quantity', 'UnitPrice']]
y = df['Country']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

"""**Logistic Regression**"""

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

lr_acc = accuracy_score(y_test, lr_pred)

print("Accuracy:", lr_acc)
print(confusion_matrix(y_test, lr_pred))

"""**Decision Tree**"""

from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()

dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

dt_acc = accuracy_score(y_test, dt_pred)

print("Accuracy:", dt_acc)
print(confusion_matrix(y_test, dt_pred))

"""**KNN**"""

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

knn_pred = knn.predict(X_test)

knn_acc = accuracy_score(y_test, knn_pred)

print("Accuracy:", knn_acc)
print(confusion_matrix(y_test, knn_pred))

"""**COMPARE MODELS**"""

models = [
    'Logistic Regression',
    'Decision Tree',
    'KNN'
]

accuracies = [
    lr_acc,
    dt_acc,
    knn_acc
]


print("MODEL COMPARISON")

for model, acc in zip(models, accuracies):
    print(model, ":", round(acc*100,2), "%")

"""**Accuracy Comparison Graph**"""

models = ['Logistic Regression', 'Decision Tree', 'KNN']
accuracy = [lr_acc, dt_acc, knn_acc]

plt.figure(figsize=(8,5))
plt.bar(models, accuracy)

plt.title("Model Accuracy Comparison")
plt.ylabel("Accuracy")
plt.show()

best_model = models[np.argmax(accuracies)]
best_accuracy = max(accuracies)

print("\nBest Model =", best_model)
print("Best Accuracy =", round(best_accuracy*100,2), "%")